### ISSUE TITLE
questions about plots: SRER

### ISSUE THREAD

**Issue by lizzieinvancouver** [ngoj1/arizonamoisture#1]
@ngoj1 Good plots, but weird data! It is always annoying to have it every 30 minutes, but fairly common (for precip I would usually sum by day and start by plotting that). 

**Does SRER not provide any soil moisture?** 

Looking at your plots and @JulieSieg -- I feel like the moisture plots are much more interesting and more relevant to plants as a metric of 'resource' available so if SRER does not have any soil moisture we can skip any further work on it. 

**SRER is the NEON site, right?**

**Comment by ngoj1** [comment]
So I checked the NEON data just now and SRER does actually have soil moisture content like Jornada does. I probably just missed it, but I don't remember seeing soil moisture aside from general soil chemical properties the last few times I checked. Anyway, I can visualize this as well before making the new plots so we can compare and see which site is preferred.

**Comment by lizzieinvancouver** [comment]
@ngoj1 If easy, that would be good, but not critical at all.

**Comment by ngoj1** [comment]
I've downloaded the relevant data package, but suddenly facing an issue about "file path too long" when I try to unzip. This didn't  occur previously with the rainfall data from SRER, and I'm not sure how to go around this because I can't edit folder names while they're still zipped and between 2017 and 2022 there are far too many folders to rename even if I could. I can bring this up next scrum to see if anyone has a solution, as the only one I've found so far is going into Registry editor and changing some system preferences which I don't want to do for fear of messing up some other things.

**Comment by lizzieinvancouver** [comment]
@ngoj1 That's bizarre! You should ask at scrum ... also check if NEON has any sort of help or contact email/webform? It sounds like they perhaps have corrupted their own files .....

**Comment by ngoj1** [comment]
I figured it out; it seems like extracting it in a bunch of sub folders makes the path itself too long, but if you extract it in C:/ then it works fine. I'll do the same data transformation to this as I did with the SRER precipitation and see how the soil moisture patterns compare to Jornada

**Comment by ngoj1** [comment]
A quick visualization of the data shows even more obscure of a rainfall pattern than the Jornada data; 
Here's 2018, 2019, 2020, 2021, and 2022
![image](https://github.com/ngoj1/arizonamoisture/assets/87724921/0a2ae9a6-6c9b-4618-aee5-8979db38f408)
![image](https://github.com/ngoj1/arizonamoisture/assets/87724921/22a21e7d-ddef-472d-9ec9-f212c48beaf0)
![image](https://github.com/ngoj1/arizonamoisture/assets/87724921/7a2db082-6420-4d8c-b455-6a80e2d37395)
![image](https://github.com/ngoj1/arizonamoisture/assets/87724921/77090faa-b1ca-4a70-834b-d89b11803209)
![image](https://github.com/ngoj1/arizonamoisture/assets/87724921/9e4dea9d-ec37-4d33-9871-8f6e8a97f0de)

Should we still pursue with this dataset or is Jornada sufficient?

**Comment by lizzieinvancouver** [comment]
@ngoj1 Nice work! This data looks a little spotty too; let's stick with the Jornada, but thank you for working on this! I think we can close this issue when you're ready.
