### ISSUE TITLE
plots for Jornada

### ISSUE THREAD

**Issue by lizzieinvancouver** [ngoj1/arizonamoisture#2]
@ngoj1 The Jornada plots are great! My only suggestion would be to plot DOY, but try to add labels for several months (if easy) as that's helpful to see seasonality.

I have a couple requests also:

- [ ] Can you make the same design of plots but do all sites on one page for each year? This will allow us to compare sites.
- [ ] Can you make the same design but all years on one page (and one site per page)?  This will help compare the seasonality across years -- I am interested to see how consistent it is. 

If you are using ggplot2 you can do this with facet or a similar command (ask around in scrum). If you are using base R or such you can do it with the par(mfrow=c(x, x)) type command and a for loop. If you have questions that no one can answer in scrum, feel free to post a code snippet here and I will try to help.

**Comment by ngoj1** [comment]
I've updated the plot folder so that it includes graphs faceted by year and by site (301 or 302). I think I emailed you about it when the plots were still being made, I just forgot to reply here as well on the issue.

**Comment by lizzieinvancouver** [comment]
@ngoj1 Awesome! Let's close this issue then.
